### PR TITLE
Ghost Tapping fix & Better dialogue box lol

### PR DESCRIPTION
**Pull request by SpunBlue**
your WHALECUM (haha funny whale sperm joke)

- Added a single line of code to disable the miss animations in Ghost-Tapping (Playstate)
- Fixed up the Dialogue Boxes to make them less shitty and ready for modding (Dialoguebox)
- Added Portraits of the Characters (I believe i added all of them) (Assets)
- Modified the Read Me to have Credits for the resources i used for the Dialogue Boxes (Readme)

### CODE REVIEW

**Review by thepercentageguy — CHANGES_REQUESTED** [review]
Literally no description of the changes in the description, idk what I'm looking for, i cannot review this.

**Comment by SpunBlue** [comment]
ok fixed it i think

**Review by thepercentageguy — COMMENTED** [review]
What do you mean by
> Fixed up the Dialogue Boxes to make them less shitty and ready for modding

**Comment by SpunBlue** [comment]
> What do you mean by
> 
> > Fixed up the Dialogue Boxes to make them less shitty and ready for modding

I made them look better and made it so people don't have to add the regular dialogue box sprite and stuff that ya know requires you to modify in the dialogue box code when you make mods, just makes it a lil easier.

**Comment by thepercentageguy** [comment]
> 
> > What do you mean by
> > 
> > > Fixed up the Dialogue Boxes to make them less shitty and ready for modding
> 
> I made them look better and made it so people don't have to add the regular dialogue box sprite and stuff that ya know requires you to modify in the dialogue box code when you make mods, just makes it a lil easier.

What is the new process of adding dialogue

**Comment by SpunBlue** [comment]
> > > What do you mean by
> > > > Fixed up the Dialogue Boxes to make them less shitty and ready for modding
> > 
> > 
> > I made them look better and made it so people don't have to add the regular dialogue box sprite and stuff that ya know requires you to modify in the dialogue box code when you make mods, just makes it a lil easier.
> 
> What is the new process of adding dialogue

All you gotta do now is make the dialogue text file and add it in playstate like normal and then goto where the dialogue box is requested to load in schoolintro(doof) and do the normal, this way people dont have to add the non-pixelated portraits and dialogue box. and if you want it to be the pixel style you just go into dialogue box and add like a few lines of code lmao

**Review by thepercentageguy — CHANGES_REQUESTED** [review]
Remove the ghost tapping change and then i can put the changes into testing.

**Comment by SpunBlue** [comment]
> Remove the ghost tapping change and then i can put the changes into testing.

fine

**Comment by SpunBlue** [comment]
hold on tryna recompile unfnf but haxeflixel is being slow

**Comment by SpunBlue** [comment]
Okay fixed, Should automatically be updated on the PR lol

**Review by thepercentageguy — APPROVED** [review]

**Pull request merged**
